export * from './Intro';
export * from './useIntroStyles';

export const introKeywords = [
  'intro',
  'welcome',
  'party',
  'introduction',
  'front-end effects',
  'special effects',
  'ferris wheel',
  'ferris wheel icon',
  'ferris wheel animation',
  'ferris wheel svg',
  'svg animation',
  'css animation',
  'animation from scratch',
  'web development',
  'web design',
  'web designer',
  'web developer',
  'mochinski',
  'chris mochinski',
  'chris mo',
  'mo mochinski',
  'mo',
  'mo design',
  'mo design studio',
  'wreck shop',
  'wreck shop media',
  'junk fm',
  'radda radda',
  'readygoes',
];
